In [2]:
import torch
import numpy as np

In [6]:
x = torch.empty(2, 3) # Can do several dimensions

print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [23]:
x = torch.ones(2, 2, dtype=torch.int)
print(x)
print(x.dtype)
print(x.size())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32
torch.Size([2, 2])


In [ ]:
# In pytorch, every operation that has a "_" at the end, will do an in-place operation
# i.e. y.add_(x) adds x to y

In [29]:
x = torch.rand(4, 3)
print(x)
print(x[1,1].item())

# reshaping wihtout knowing one of the values
y=x.view(-1, 6)
print(y)

tensor([[0.0184, 0.9762, 0.7677],
        [0.4021, 0.5685, 0.1268],
        [0.7102, 0.9674, 0.7523],
        [0.3197, 0.3571, 0.2102]])
0.5684988498687744
tensor([[0.0184, 0.9762, 0.7677, 0.4021, 0.5685, 0.1268],
        [0.7102, 0.9674, 0.7523, 0.3197, 0.3571, 0.2102]])


In [3]:
# Be careful when using numpy arrays with torch tensors
# Maybe have a look at torch.cuda

False
